### ISSUE TITLE
Support to deploy the tag

### ISSUE THREAD

**Issue by bhagavan44** [lowply/deploy-firebase#13]
Is there a way to deploy from Tag/Release instead of the branch?

**Comment by woneiros** [comment]
I'd be interested in this as well. I was trying to trigger on a push/tag, but the `if [ "${GITHUB_REF}" != "refs/heads/${TARGET_BRANCH}" ];` keeps killing my job because it's a different ref.

**Comment by lowply** [comment]
Thank you for the feedback and apologies for the delay in replying! I'm currently a bit packed, but I'll look into this when I have more time.

**Comment by lowply** [comment]
Hi @bhagavan44 @WillahScott Thank you for your patience. I've just pushed a change and [released it as v0.0.5](https://github.com/marketplace/actions/deploy-to-firebase). Now you can deploy using tags. Let me know if you have any questions, thanks again!
