### ISSUE TITLE
Trouble setting up Build and Deploy

### ISSUE THREAD

**Issue by JamesVanWaza** [lowply/deploy-firebase#17]
Greetings @lowply , I am having a challenge, setting up the `build and deploy`. 

The first step I did, is 
1. I ran the `firebase login:ci` and got the secret key
2. I added the secret key, to `settings/secrets`
3. I copied the deploy.yml file to the `workflows` folder 
4. This is my deployed file - https://github.com/JamesVanWaza/badwf/blob/main/.github/workflows/deploy.yml
5. I am getting the following error, please assist. See screenshot attached. 

<img width="1490" alt="Screen Shot 2021-10-07 at 7 59 49 PM" src="https://user-images.githubusercontent.com/4000076/136477726-461eb6d4-44cf-43e3-a732-745a30edb22c.png">

**Comment by lowply** [comment]
Hi @JamesVanWaza I'm terribly sorry for the radio silence - as the error message describes, please make sure that you have access to the Firebase project in question. I'm closing this issue out but feel free to reopen it if you believe that something is wrong with this action.

**Comment by JamesVanWaza** [comment]
Thanks, @lowply issue revolved after firebase updated and now I can set it up automatically.
