### ISSUE TITLE
Failed to download action lowply/build-hugo

### ISSUE THREAD

**Issue by 5tigerjelly** [lowply/deploy-firebase#2]
Hello, 
I found your GitHub action on deploying to firebase. But I was unable to successfully apply this action. It keeps on failing with the response that it was unable to download `lowply/build-hugo`
```
Current runner version: '2.165.2'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@master'
Download action repository 'lowply/build-hugo@v0.0.2'
##[warning]Failed to download action 'https://api.github.com/repos/lowply/build-hugo/tarball/v0.0.2'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 20.766 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/lowply/build-hugo/tarball/v0.0.2'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 13.996 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).
```

**Comment by ibm4n** [comment]
I ran into the same problem.
`Failed to download action 'https://api.github.com/repos/lowply/build-hugo/tarball/v0.0.2'. Error Response status code does not indicate success: 404 (Not Found).`

**Comment by lowply** [comment]
@5tigerjelly @ibm4n I'm sorry that I missed you opened this issue. The example workflow in the README.md file is using build-hugo v0.0.2, but this version doesn't exist anymore. Please browse to https://github.com/lowply/build-hugo/releases and pick the latest version, for example `lowply/build-hugo@v0.68.3`.

I'll update the README.md as it's confusing. Thank you for reporting!
