### ISSUE TITLE
How do you set GitHub action env variable? (to store my firebase token)

### ISSUE THREAD

**Issue by leomet07** [lowply/deploy-firebase#3]
There isn't that much information on how to make an env variable? It isn't a good idea to store it in a public action file (when it's NOT an env var)...

**Comment by lowply** [comment]
@leomet07 your firebase token can be stored as a Secret in your repo, and you can use the value from the public workflow file like this: `${{ secrets.FIREBASE_TOKEN }}`. Please refer to [Creating and storing encrypted secrets - GitHub Help](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) for more details. Please reopen if you have any other questions. Thanks!

**Comment by leomet07** [comment]
Thank you! This worked :)
