### ISSUE TITLE
Not in a Firebase app directory (could not locate firebase.json)

### ISSUE THREAD

**Issue by Addibro** [lowply/deploy-firebase#5]
Hi!

I wonder if my action setup is missing something (other than firebase.json). Where does it look for this file? 

Thanks!

**Comment by Addibro** [comment]
Should add that this is the first time using github actions! But it seems awesome.

**Comment by lowply** [comment]
@Addibro oh hi! Before running this as GitHub Action, can you try running this in your local repository?

```
firebase deploy \
    -m "${GITHUB_SHA}" \
    --project ${FIREBASE_PROJECT} \
    --only hosting
```

If you get any error message, let me know in this issue. Thanks!

**Comment by gomano-shigure** [comment]
I was stuck by same messages in Ella.  
You must check out code before deploying as the example shows.

**Comment by lowply** [comment]
Thanks @amazyra. Now I'm closing this issue.
