### ISSUE TITLE
Does this project have build steps?

### ISSUE THREAD

**Issue by brydonm** [lowply/deploy-firebase#7]
I'd like to run `npm run build` in the dir before deploying - I'm not sure I follow the repo with being able to run custom commands (including only deploying certain targets, like hosting.)

Is this a capability in this package?

**Comment by lowply** [comment]
@Brydom yep, add another step before the `deploy-firebase` step. For instance, in your GitHub Actions workflow file, do something like this:

```
- name: Build
  run: npm run build
- name: Deploy to Firebase
  uses: lowply/deploy-firebase@v0.0.2
```

See [Workflow syntax for GitHub Actions - GitHub Help](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun) for more info.

**Comment by brydonm** [comment]
Thanks @lowply - I should have looked more into actions first!
