### ISSUE TITLE
Facing this ENOENT error ~ this morning 

### ISSUE THREAD

**Issue by absurdfounder** [lowply/deploy-firebase#9]
@lowply 

`Sending build context to Docker daemon  9.216kB

Step 1/4 : FROM node:10-slim
 ---> 264968c6acc1
Step 2/4 : RUN npm install -g firebase-tools
 ---> Running in ea97db582b77
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/firebase-tools/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/DABH/diagnostics.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T08_20_32_745Z-debug.log
The command '/bin/sh -c npm install -g firebase-tools' returned a non-zero code: 1

##[error]Docker build failed with exit code 1`

**Comment by krystianjj** [comment]
It's look like command git not work. 
I resolve this by adding ```RUN apk add --no-cache git``` before install -g firebase-tools

**Comment by absurdfounder** [comment]
did you update the workflow script for the action ?

if not, should i add in the yml workflow file ?

**Comment by krystianjj** [comment]
It's look like git was removed from docker node-alpine and node-slim

If you using gitlba-ci.yml you muse add command to install git before you run install firebase-tools

**Comment by absurdfounder** [comment]
I am just using the worker yml file with firebase deploy code, with default setup in firebase.json , .firebaserc & .gitignore

**Comment by absurdfounder** [comment]
Can you update the your docker version file to support the function ? as the worker runs from your docker files.


![Screenshot 2020-06-22 at 3 22 03 PM](https://user-images.githubusercontent.com/25829699/85274198-3e385b00-b49c-11ea-8344-3b5ff4c8c690.png)

**Comment by krystianjj** [comment]
You must write to @lowply or create merge request with this changes.

**Comment by lowply** [comment]
Thank you @SuperHuman12 for opening this issue and thank you @krystianjj for your help 😄 Will take a look shortly.

**Comment by absurdfounder** [comment]
@lowply @krystianjj 

Hey guys, do you know how can this worker file be used to only publish only releases ?
I am trying to manage based on versions, like every release version that i create to then be deployed to firebase.
